---
- name: Setup jail for borg backup
  hosts: localhost
  connection: local
  tasks:
    - name: Ensure sshd is started and enabled
      service:
        state: started
        name: sshd
        enabled: yes
